package com.example.islam.dmitask.db.dto;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table BOOK_DETAIL.
 */
public class BookDetail {

    private String id;
    private String title;
    private Double price;
    private String image;
    private String author;
    private String link;

    public BookDetail() {
    }

    public BookDetail(String id) {
        this.id = id;
    }

    public BookDetail(String id, String title, Double price, String image, String author, String link) {
        this.id = id;
        this.title = title;
        this.price = price;
        this.image = image;
        this.author = author;
        this.link = link;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getLink() {
        return link;
    }

    public void setLink(String link) {
        this.link = link;
    }

}
