package com.example.islam.dmitask.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.example.islam.dmitask.db.dbhelper.DaoSession;
import com.example.islam.dmitask.db.dto.BookDetail;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table BOOK_DETAIL.
 */
public class BookDetailDao extends AbstractDao<BookDetail, String> {

    public static final String TABLENAME = "BOOK_DETAIL";

    public BookDetailDao(DaoConfig config) {
        super(config);
    }

    ;


    public BookDetailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /**
     * Creates the underlying database table.
     */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'BOOK_DETAIL' (" + //
                "'ID' TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "'TITLE' TEXT," + // 1: title
                "'PRICE' REAL," + // 2: price
                "'IMAGE' TEXT," + // 3: image
                "'AUTHOR' TEXT," + // 4: author
                "'LINK' TEXT);"); // 5: link
    }

    /**
     * Drops the underlying database table.
     */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BOOK_DETAIL'";
        db.execSQL(sql);
    }

    /**
     * @inheritdoc
     */
    @Override
    protected void bindValues(SQLiteStatement stmt, BookDetail entity) {
        stmt.clearBindings();

        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }

        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }

        Double price = entity.getPrice();
        if (price != null) {
            stmt.bindDouble(3, price);
        }

        String image = entity.getImage();
        if (image != null) {
            stmt.bindString(4, image);
        }

        String author = entity.getAuthor();
        if (author != null) {
            stmt.bindString(5, author);
        }

        String link = entity.getLink();
        if (link != null) {
            stmt.bindString(6, link);
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }

    /**
     * @inheritdoc
     */
    @Override
    public BookDetail readEntity(Cursor cursor, int offset) {
        BookDetail entity = new BookDetail( //
                cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
                cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
                cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2), // price
                cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // image
                cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // author
                cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // link
        );
        return entity;
    }

    /**
     * @inheritdoc
     */
    @Override
    public void readEntity(Cursor cursor, BookDetail entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPrice(cursor.isNull(offset + 2) ? null : cursor.getDouble(offset + 2));
        entity.setImage(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setAuthor(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setLink(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
    }

    /**
     * @inheritdoc
     */
    @Override
    protected String updateKeyAfterInsert(BookDetail entity, long rowId) {
        return entity.getId();
    }

    /**
     * @inheritdoc
     */
    @Override
    public String getKey(BookDetail entity) {
        if (entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /**
     * @inheritdoc
     */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }

    /**
     * Properties of entity BookDetail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Price = new Property(2, Double.class, "price", false, "PRICE");
        public final static Property Image = new Property(3, String.class, "image", false, "IMAGE");
        public final static Property Author = new Property(4, String.class, "author", false, "AUTHOR");
        public final static Property Link = new Property(5, String.class, "link", false, "LINK");
    }

}
